name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: download VPP
        uses: actions/checkout@v2
        with:
          repository: FDio/vpp
          ref: v21.06
          path: vpp
      - name: install libmemif
        run: |
          cd $HOME
          mv $GITHUB_WORKSPACE/vpp $HOME/
          mkdir libmemif-build && cd libmemif-build
          cmake ../vpp/extras/libmemif
          make
          sudo make install
          sudo ldconfig
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          npm install
          npm run build
          npm test
      - name: check code style
        run: |
          npm run lint
          npm run clang-format
          git diff --exit-code
