name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download VPP
        uses: actions/checkout@v3
        with:
          repository: FDio/vpp
          ref: v22.02
          path: vpp
      - name: Install libmemif
        run: |
          cd $HOME
          mv $GITHUB_WORKSPACE/vpp $HOME/
          mkdir libmemif-build && cd libmemif-build
          cmake ../vpp/extras/libmemif
          make
          sudo make install
          sudo ldconfig
      - uses: actions/checkout@v2
      - name: Build and test
        run: |
          corepack pnpm install
          corepack pnpm build
          corepack pnpm typecheck
          corepack pnpm test
      - name: Check code style
        run: |
          corepack pnpm lint
          corepack pnpm clang-format
          git diff --exit-code
